# Generated by Django 5.0.7 on 2024-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='label',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='LinkLabel',
        ),
    ]
