# Generated by Django 5.0.7 on 2024-09-10 10:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_links_label_delete_linklabel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='links',
            unique_together={('link', 'created_by')},
        ),
    ]
