# Generated by Django 5.0.7 on 2024-10-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_profile_picture_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
